<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../.resources/report.css" type="text/css"/><link rel="shortcut icon" href="../.resources/report.gif" type="image/gif"/><title>MethodRoadie.java</title><link rel="stylesheet" href="../.resources/prettify.css" type="text/css"/><script type="text/javascript" src="../.resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../.sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">Junit-r4.11</a> &gt; <a href="index.source.html" class="el_package">org.junit.internal.runners</a> &gt; <span class="el_source">MethodRoadie.java</span></div><h1>MethodRoadie.java</h1><pre class="source lang-java linenums">package org.junit.internal.runners;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import org.junit.internal.AssumptionViolatedException;
import org.junit.runner.Description;
import org.junit.runner.notification.Failure;
import org.junit.runner.notification.RunNotifier;
import org.junit.runners.BlockJUnit4ClassRunner;

/**
 * @deprecated Included for backwards compatibility with JUnit 4.4. Will be
 *             removed in the next release. Please use
 *             {@link BlockJUnit4ClassRunner} in place of {@link JUnit4ClassRunner}.
 */
@Deprecated
public class MethodRoadie {
    private final Object fTest;
    private final RunNotifier fNotifier;
    private final Description fDescription;
    private TestMethod fTestMethod;

<span class="fc" id="L31">    public MethodRoadie(Object test, TestMethod method, RunNotifier notifier, Description description) {</span>
<span class="fc" id="L32">        fTest = test;</span>
<span class="fc" id="L33">        fNotifier = notifier;</span>
<span class="fc" id="L34">        fDescription = description;</span>
<span class="fc" id="L35">        fTestMethod = method;</span>
<span class="fc" id="L36">    }</span>

    public void run() {
<span class="pc bpc" id="L39" title="1 of 2 branches missed.">        if (fTestMethod.isIgnored()) {</span>
<span class="nc" id="L40">            fNotifier.fireTestIgnored(fDescription);</span>
<span class="nc" id="L41">            return;</span>
        }
<span class="fc" id="L43">        fNotifier.fireTestStarted(fDescription);</span>
        try {
<span class="fc" id="L45">            long timeout = fTestMethod.getTimeout();</span>
<span class="pc bpc" id="L46" title="1 of 2 branches missed.">            if (timeout &gt; 0) {</span>
<span class="nc" id="L47">                runWithTimeout(timeout);</span>
            } else {
<span class="fc" id="L49">                runTest();</span>
            }
        } finally {
<span class="pc" id="L52">            fNotifier.fireTestFinished(fDescription);</span>
<span class="fc" id="L53">        }</span>
<span class="fc" id="L54">    }</span>

    private void runWithTimeout(final long timeout) {
<span class="nc" id="L57">        runBeforesThenTestThenAfters(new Runnable() {</span>

            public void run() {
<span class="nc" id="L60">                ExecutorService service = Executors.newSingleThreadExecutor();</span>
<span class="nc" id="L61">                Callable&lt;Object&gt; callable = new Callable&lt;Object&gt;() {</span>
                    public Object call() throws Exception {
<span class="nc" id="L63">                        runTestMethod();</span>
<span class="nc" id="L64">                        return null;</span>
                    }
                };
<span class="nc" id="L67">                Future&lt;Object&gt; result = service.submit(callable);</span>
<span class="nc" id="L68">                service.shutdown();</span>
                try {
<span class="nc" id="L70">                    boolean terminated = service.awaitTermination(timeout,</span>
                            TimeUnit.MILLISECONDS);
<span class="nc bnc" id="L72" title="All 2 branches missed.">                    if (!terminated) {</span>
<span class="nc" id="L73">                        service.shutdownNow();</span>
                    }
<span class="nc" id="L75">                    result.get(0, TimeUnit.MILLISECONDS); // throws the exception if one occurred during the invocation</span>
<span class="nc" id="L76">                } catch (TimeoutException e) {</span>
<span class="nc" id="L77">                    addFailure(new Exception(String.format(&quot;test timed out after %d milliseconds&quot;, timeout)));</span>
<span class="nc" id="L78">                } catch (Exception e) {</span>
<span class="nc" id="L79">                    addFailure(e);</span>
<span class="nc" id="L80">                }</span>
<span class="nc" id="L81">            }</span>
        });
<span class="nc" id="L83">    }</span>

    public void runTest() {
<span class="fc" id="L86">        runBeforesThenTestThenAfters(new Runnable() {</span>
            public void run() {
<span class="fc" id="L88">                runTestMethod();</span>
<span class="fc" id="L89">            }</span>
        });
<span class="fc" id="L91">    }</span>

    public void runBeforesThenTestThenAfters(Runnable test) {
        try {
<span class="fc" id="L95">            runBefores();</span>
<span class="fc" id="L96">            test.run();</span>
<span class="nc" id="L97">        } catch (FailedBefore e) {</span>
<span class="nc" id="L98">        } catch (Exception e) {</span>
<span class="nc" id="L99">            throw new RuntimeException(&quot;test should never throw an exception to this level&quot;);</span>
        } finally {
<span class="pc" id="L101">            runAfters();</span>
<span class="pc" id="L102">        }</span>
<span class="fc" id="L103">    }</span>

    protected void runTestMethod() {
        try {
<span class="fc" id="L107">            fTestMethod.invoke(fTest);</span>
<span class="pc bpc" id="L108" title="1 of 2 branches missed.">            if (fTestMethod.expectsException()) {</span>
<span class="nc" id="L109">                addFailure(new AssertionError(&quot;Expected exception: &quot; + fTestMethod.getExpectedException().getName()));</span>
            }
<span class="fc" id="L111">        } catch (InvocationTargetException e) {</span>
<span class="fc" id="L112">            Throwable actual = e.getTargetException();</span>
<span class="pc bpc" id="L113" title="1 of 2 branches missed.">            if (actual instanceof AssumptionViolatedException) {</span>
<span class="nc" id="L114">                return;</span>
<span class="pc bpc" id="L115" title="1 of 2 branches missed.">            } else if (!fTestMethod.expectsException()) {</span>
<span class="fc" id="L116">                addFailure(actual);</span>
<span class="nc bnc" id="L117" title="All 2 branches missed.">            } else if (fTestMethod.isUnexpected(actual)) {</span>
<span class="nc" id="L118">                String message = &quot;Unexpected exception, expected&lt;&quot; + fTestMethod.getExpectedException().getName() + &quot;&gt; but was&lt;&quot;</span>
                        + actual.getClass().getName() + &quot;&gt;&quot;;
<span class="nc" id="L120">                addFailure(new Exception(message, actual));</span>
            }
<span class="nc" id="L122">        } catch (Throwable e) {</span>
<span class="nc" id="L123">            addFailure(e);</span>
<span class="fc" id="L124">        }</span>
<span class="fc" id="L125">    }</span>

    private void runBefores() throws FailedBefore {
        try {
            try {
<span class="fc" id="L130">                List&lt;Method&gt; befores = fTestMethod.getBefores();</span>
<span class="pc bpc" id="L131" title="1 of 2 branches missed.">                for (Method before : befores) {</span>
<span class="nc" id="L132">                    before.invoke(fTest);</span>
<span class="nc" id="L133">                }</span>
<span class="nc" id="L134">            } catch (InvocationTargetException e) {</span>
<span class="nc" id="L135">                throw e.getTargetException();</span>
<span class="fc" id="L136">            }</span>
<span class="nc" id="L137">        } catch (AssumptionViolatedException e) {</span>
<span class="nc" id="L138">            throw new FailedBefore();</span>
<span class="nc" id="L139">        } catch (Throwable e) {</span>
<span class="nc" id="L140">            addFailure(e);</span>
<span class="nc" id="L141">            throw new FailedBefore();</span>
<span class="fc" id="L142">        }</span>
<span class="fc" id="L143">    }</span>

    private void runAfters() {
<span class="fc" id="L146">        List&lt;Method&gt; afters = fTestMethod.getAfters();</span>
<span class="pc bpc" id="L147" title="1 of 2 branches missed.">        for (Method after : afters) {</span>
            try {
<span class="nc" id="L149">                after.invoke(fTest);</span>
<span class="nc" id="L150">            } catch (InvocationTargetException e) {</span>
<span class="nc" id="L151">                addFailure(e.getTargetException());</span>
<span class="nc" id="L152">            } catch (Throwable e) {</span>
<span class="nc" id="L153">                addFailure(e); // Untested, but seems impossible</span>
<span class="nc" id="L154">            }</span>
<span class="nc" id="L155">        }</span>
<span class="fc" id="L156">    }</span>

    protected void addFailure(Throwable e) {
<span class="fc" id="L159">        fNotifier.fireTestFailure(new Failure(fDescription, e));</span>
<span class="fc" id="L160">    }</span>
}

</pre><div class="footer"><span class="right">Created with <a href="http://www.eclemma.org/jacoco">JaCoCo</a> 0.7.0.201403182114</span></div></body></html>