<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../.resources/report.css" type="text/css"/><link rel="shortcut icon" href="../.resources/report.gif" type="image/gif"/><title>ClassRoadie.java</title><link rel="stylesheet" href="../.resources/prettify.css" type="text/css"/><script type="text/javascript" src="../.resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../.sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">Junit-r4.11</a> &gt; <a href="index.source.html" class="el_package">org.junit.internal.runners</a> &gt; <span class="el_source">ClassRoadie.java</span></div><h1>ClassRoadie.java</h1><pre class="source lang-java linenums">package org.junit.internal.runners;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;

import org.junit.runner.Description;
import org.junit.runner.notification.Failure;
import org.junit.runner.notification.RunNotifier;
import org.junit.runners.BlockJUnit4ClassRunner;

/**
 * @deprecated Included for backwards compatibility with JUnit 4.4. Will be
 *             removed in the next release. Please use
 *             {@link BlockJUnit4ClassRunner} in place of {@link JUnit4ClassRunner}.
 */
@Deprecated
public class ClassRoadie {
    private RunNotifier fNotifier;
    private TestClass fTestClass;
    private Description fDescription;
    private final Runnable fRunnable;

    public ClassRoadie(RunNotifier notifier, TestClass testClass,
<span class="fc" id="L25">            Description description, Runnable runnable) {</span>
<span class="fc" id="L26">        fNotifier = notifier;</span>
<span class="fc" id="L27">        fTestClass = testClass;</span>
<span class="fc" id="L28">        fDescription = description;</span>
<span class="fc" id="L29">        fRunnable = runnable;</span>
<span class="fc" id="L30">    }</span>

    protected void runUnprotected() {
<span class="fc" id="L33">        fRunnable.run();</span>
<span class="fc" id="L34">    }</span>

    ;

    protected void addFailure(Throwable targetException) {
<span class="nc" id="L39">        fNotifier.fireTestFailure(new Failure(fDescription, targetException));</span>
<span class="nc" id="L40">    }</span>

    public void runProtected() {
        try {
<span class="fc" id="L44">            runBefores();</span>
<span class="fc" id="L45">            runUnprotected();</span>
<span class="nc" id="L46">        } catch (FailedBefore e) {</span>
        } finally {
<span class="pc" id="L48">            runAfters();</span>
<span class="pc" id="L49">        }</span>
<span class="fc" id="L50">    }</span>

    private void runBefores() throws FailedBefore {
        try {
            try {
<span class="fc" id="L55">                List&lt;Method&gt; befores = fTestClass.getBefores();</span>
<span class="pc bpc" id="L56" title="1 of 2 branches missed.">                for (Method before : befores) {</span>
<span class="nc" id="L57">                    before.invoke(null);</span>
<span class="nc" id="L58">                }</span>
<span class="nc" id="L59">            } catch (InvocationTargetException e) {</span>
<span class="nc" id="L60">                throw e.getTargetException();</span>
<span class="fc" id="L61">            }</span>
<span class="nc" id="L62">        } catch (org.junit.internal.AssumptionViolatedException e) {</span>
<span class="nc" id="L63">            throw new FailedBefore();</span>
<span class="nc" id="L64">        } catch (Throwable e) {</span>
<span class="nc" id="L65">            addFailure(e);</span>
<span class="nc" id="L66">            throw new FailedBefore();</span>
<span class="fc" id="L67">        }</span>
<span class="fc" id="L68">    }</span>

    private void runAfters() {
<span class="fc" id="L71">        List&lt;Method&gt; afters = fTestClass.getAfters();</span>
<span class="pc bpc" id="L72" title="1 of 2 branches missed.">        for (Method after : afters) {</span>
            try {
<span class="nc" id="L74">                after.invoke(null);</span>
<span class="nc" id="L75">            } catch (InvocationTargetException e) {</span>
<span class="nc" id="L76">                addFailure(e.getTargetException());</span>
<span class="nc" id="L77">            } catch (Throwable e) {</span>
<span class="nc" id="L78">                addFailure(e); // Untested, but seems impossible</span>
<span class="nc" id="L79">            }</span>
<span class="nc" id="L80">        }</span>
<span class="fc" id="L81">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.eclemma.org/jacoco">JaCoCo</a> 0.7.0.201403182114</span></div></body></html>