Testsuite: org.apache.commons.io.IOExceptionWithCauseTestCase
Tests run: 2, Failures: 0, Errors: 0, Time elapsed: 0 sec

Testcase: testIOExceptionThrowable took 0 sec
Testcase: testIOExceptionStringThrowable took 0 sec
